#!/bin/bash
# =============================================================================
# Matrix Server Setup Script
# Generates deployment configuration files from templates
# =============================================================================

set -e

# Get script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TEMPLATE_DIR="${SCRIPT_DIR}/templates"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Default values
DEPLOY_DIR="${SCRIPT_DIR}/deploy"
ALLOW_REGISTRATION="false"
ALLOW_FEDERATION="true"
ROCKSDB_CACHE_MB="256"

# Print banner
echo -e "${BLUE}"
echo "=============================================="
echo "       Matrix Server Setup Script"
echo "=============================================="
echo -e "${NC}"

# Check if templates exist
if [[ ! -d "$TEMPLATE_DIR" ]]; then
    echo -e "${RED}Error: Templates directory not found at ${TEMPLATE_DIR}${NC}"
    exit 1
fi

# Function to prompt for required input
prompt_required() {
    local var_name="$1"
    local prompt_text="$2"
    local value=""
    
    while [[ -z "$value" ]]; do
        read -p "$prompt_text: " value
        if [[ -z "$value" ]]; then
            echo -e "${RED}This field is required.${NC}"
        fi
    done
    echo "$value"
}

# Function to prompt for optional input with default
prompt_optional() {
    local prompt_text="$1"
    local default="$2"
    local value=""
    
    read -p "$prompt_text [$default]: " value
    echo "${value:-$default}"
}

# Function to prompt yes/no
prompt_yesno() {
    local prompt_text="$1"
    local default="$2"
    local value=""
    
    read -p "$prompt_text (y/n) [$default]: " value
    value="${value:-$default}"
    if [[ "$value" =~ ^[Yy] ]]; then
        echo "true"
    else
        echo "false"
    fi
}

# Function to generate random string
generate_secret() {
    openssl rand -hex "$1" 2>/dev/null || head -c "$1" /dev/urandom | xxd -p | tr -d '\n' | head -c "$((2 * $1))"
}

# Function to process template file
process_template() {
    local template_file="$1"
    local output_file="$2"
    
    sed -e "s|{{MATRIX_DOMAIN}}|${MATRIX_DOMAIN}|g" \
        -e "s|{{LIVEKIT_DOMAIN}}|${LIVEKIT_DOMAIN}|g" \
        -e "s|{{ADMIN_EMAIL}}|${ADMIN_EMAIL}|g" \
        -e "s|{{ALLOW_REGISTRATION}}|${ALLOW_REGISTRATION}|g" \
        -e "s|{{ALLOW_FEDERATION}}|${ALLOW_FEDERATION}|g" \
        -e "s|{{ROCKSDB_CACHE_MB}}|${ROCKSDB_CACHE_MB}|g" \
        -e "s|{{LIVEKIT_API_KEY}}|${LIVEKIT_API_KEY}|g" \
        -e "s|{{LIVEKIT_API_SECRET}}|${LIVEKIT_API_SECRET}|g" \
        "$template_file" > "$output_file"
}

echo -e "${YELLOW}Please provide the following information:${NC}\n"

# Gather configuration
MATRIX_DOMAIN=$(prompt_required "MATRIX_DOMAIN" "Matrix server domain (e.g., matrix.example.com)")
LIVEKIT_DOMAIN=$(prompt_required "LIVEKIT_DOMAIN" "LiveKit server domain (e.g., livekit.example.com)")
ADMIN_EMAIL=$(prompt_required "ADMIN_EMAIL" "Admin email (for Let's Encrypt)")

echo ""
echo -e "${YELLOW}Optional configuration (press Enter for defaults):${NC}\n"

ALLOW_REGISTRATION=$(prompt_yesno "Allow public registration?" "n")
ALLOW_FEDERATION=$(prompt_yesno "Allow federation with other servers?" "y")
ROCKSDB_CACHE_MB=$(prompt_optional "RocksDB cache size in MB" "256")

# Generate LiveKit API credentials
echo ""
echo -e "${BLUE}Generating LiveKit API credentials...${NC}"
LIVEKIT_API_KEY=$(generate_secret 16)
LIVEKIT_API_SECRET=$(generate_secret 32)

# Create deploy directory
echo ""
echo -e "${BLUE}Creating deployment directory...${NC}"
mkdir -p "$DEPLOY_DIR"

# Process templates
echo -e "${BLUE}Processing templates...${NC}"

echo "  - docker-compose.yml"
cp "$TEMPLATE_DIR/docker-compose.yml" "$DEPLOY_DIR/docker-compose.yml"

echo "  - conduit.toml"
process_template "$TEMPLATE_DIR/conduit.toml" "$DEPLOY_DIR/conduit.toml"

echo "  - livekit.yaml"
process_template "$TEMPLATE_DIR/livekit.yaml" "$DEPLOY_DIR/livekit.yaml"

echo "  - Caddyfile"
process_template "$TEMPLATE_DIR/Caddyfile" "$DEPLOY_DIR/Caddyfile"

# Generate .env file with credentials
echo "  - .env"
cat > "$DEPLOY_DIR/.env" << EOF
# =============================================================================
# Matrix Server Environment Configuration
# Generated by setup.sh on $(date)
# =============================================================================

# Domain Configuration
MATRIX_DOMAIN=${MATRIX_DOMAIN}
LIVEKIT_DOMAIN=${LIVEKIT_DOMAIN}
ADMIN_EMAIL=${ADMIN_EMAIL}

# LiveKit API Credentials (keep secret!)
LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}

# Conduit Configuration
ALLOW_REGISTRATION=${ALLOW_REGISTRATION}
ALLOW_FEDERATION=${ALLOW_FEDERATION}
ROCKSDB_CACHE_MB=${ROCKSDB_CACHE_MB}
EOF

# Print summary
echo ""
echo -e "${GREEN}=============================================="
echo "       Setup Complete!"
echo "==============================================${NC}"
echo ""
echo -e "Deployment files created in: ${BLUE}${DEPLOY_DIR}/${NC}"
echo ""
echo -e "${YELLOW}Files generated:${NC}"
echo "  - docker-compose.yml"
echo "  - conduit.toml"
echo "  - livekit.yaml"
echo "  - Caddyfile"
echo "  - .env (contains secrets)"
echo ""
echo -e "${YELLOW}LiveKit API Credentials (save these!):${NC}"
echo -e "  API Key:    ${BLUE}${LIVEKIT_API_KEY}${NC}"
echo -e "  API Secret: ${BLUE}${LIVEKIT_API_SECRET}${NC}"
echo ""
echo -e "${YELLOW}DNS Records Required:${NC}"
echo "  A record: ${MATRIX_DOMAIN} -> Your Server IP"
echo "  A record: ${LIVEKIT_DOMAIN} -> Your Server IP"
echo ""
echo -e "${YELLOW}Firewall Ports Required:${NC}"
echo "  TCP: 80, 443, 8448, 5349"
echo "  UDP: 443, 7882"
echo ""
echo -e "${YELLOW}To start the server:${NC}"
echo -e "  cd ${DEPLOY_DIR}"
echo "  docker compose up -d"
echo ""
echo -e "${YELLOW}To view logs:${NC}"
echo "  docker compose logs -f"
echo ""
